// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EeeeeeClient is the client API for Eeeeee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EeeeeeClient interface {
	SayHello222(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type eeeeeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEeeeeeClient(cc grpc.ClientConnInterface) EeeeeeClient {
	return &eeeeeeClient{cc}
}

func (c *eeeeeeClient) SayHello222(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aa.bb.Eeeeee/SayHello222", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EeeeeeServer is the server API for Eeeeee service.
// All implementations must embed UnimplementedEeeeeeServer
// for forward compatibility
type EeeeeeServer interface {
	SayHello222(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedEeeeeeServer()
}

// UnimplementedEeeeeeServer must be embedded to have forward compatible implementations.
type UnimplementedEeeeeeServer struct {
}

func (UnimplementedEeeeeeServer) SayHello222(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello222 not implemented")
}
func (UnimplementedEeeeeeServer) mustEmbedUnimplementedEeeeeeServer() {}

// UnsafeEeeeeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EeeeeeServer will
// result in compilation errors.
type UnsafeEeeeeeServer interface {
	mustEmbedUnimplementedEeeeeeServer()
}

func RegisterEeeeeeServer(s grpc.ServiceRegistrar, srv EeeeeeServer) {
	s.RegisterService(&Eeeeee_ServiceDesc, srv)
}

func _Eeeeee_SayHello222_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EeeeeeServer).SayHello222(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aa.bb.Eeeeee/SayHello222",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EeeeeeServer).SayHello222(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Eeeeee_ServiceDesc is the grpc.ServiceDesc for Eeeeee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eeeeee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aa.bb.Eeeeee",
	HandlerType: (*EeeeeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello222",
			Handler:    _Eeeeee_SayHello222_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ee.proto",
}
