// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GgServiceClient is the client API for GgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GgServiceClient interface {
	SayHelloFor(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type ggServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGgServiceClient(cc grpc.ClientConnInterface) GgServiceClient {
	return &ggServiceClient{cc}
}

func (c *ggServiceClient) SayHelloFor(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aa.bb.GgService/SayHelloFor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GgServiceServer is the server API for GgService service.
// All implementations must embed UnimplementedGgServiceServer
// for forward compatibility
type GgServiceServer interface {
	SayHelloFor(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGgServiceServer()
}

// UnimplementedGgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGgServiceServer struct {
}

func (UnimplementedGgServiceServer) SayHelloFor(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloFor not implemented")
}
func (UnimplementedGgServiceServer) mustEmbedUnimplementedGgServiceServer() {}

// UnsafeGgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GgServiceServer will
// result in compilation errors.
type UnsafeGgServiceServer interface {
	mustEmbedUnimplementedGgServiceServer()
}

func RegisterGgServiceServer(s grpc.ServiceRegistrar, srv GgServiceServer) {
	s.RegisterService(&GgService_ServiceDesc, srv)
}

func _GgService_SayHelloFor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GgServiceServer).SayHelloFor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aa.bb.GgService/SayHelloFor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GgServiceServer).SayHelloFor(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GgService_ServiceDesc is the grpc.ServiceDesc for GgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aa.bb.GgService",
	HandlerType: (*GgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloFor",
			Handler:    _GgService_SayHelloFor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Gg.proto",
}
